#!/bin/bash
#SBATCH --output=%x.%j.log
#SBATCH --job-name=match_TT
#SBATCH --qos=np
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=4
#SBATCH --hint=nomultithread
#SBATCH --time=6:00:00

module load python3
module load ecmwf-toolbox

python3 3_matched_lat_lon_time_v13_save_cams_aod.py
#python3 4_matched_lat_lon_time_v13_save_variance.py
python3 5_co-located_cams_atlid_uncertainty.py 
python3 6_uncertainty_co-located_cams_atlid_filter_uncertainty.py
python3 7_uncertainty_co-located_cams_atlid.py
